services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: yancotta/brim_invoice_nextjs_backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/invoices"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
    image: yancotta/brim_invoice_nextjs_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy