services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: yancotta/brim_invoice_nextjs_backend:sqlite-s3
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./invoices.db:/app/invoices.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/invoices"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
    image: yancotta/brim_invoice_nextjs_frontend:sqlite-s3
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy